#!/usr/bin/env python3
"""Regenerate sw.js with a fresh precache list and version.

Run from the repo root after adding new pages or assets, then commit sw.js.
Ordinary content edits do NOT require regeneration — the service worker
revalidates cached files in the background on every visit.
"""
import glob
import hashlib
import json

ASSETS = sorted(
    glob.glob("*.html") + glob.glob("*/*.html")
    + glob.glob("*.css")
    + glob.glob("*.js") + glob.glob("*/*.js")
    + glob.glob("*.png") + glob.glob("*/img/*.png") + glob.glob("*/img/*.jpg")
    + ["manifest.webmanifest"]
)
ASSETS = [a for a in ASSETS if a != "gen-sw.py"]
# cache directory URLs for the index pages too
urls = ["./"] + ["./" + a for a in ASSETS]
urls += ["./engines/", "./frr/"]

# Bump SW_REV to force a new cache even when the asset list is unchanged
# (e.g. after changing the service worker strategy itself).
SW_REV = "3"
# version = hash of the asset list + revision, so the precache re-runs when
# pages are added/removed or the strategy changes
version = hashlib.sha1((SW_REV + "|" + "|".join(urls)).encode()).hexdigest()[:10]

sw = f"""// Generated by gen-sw.py — do not edit by hand.
// Strategy: precache everything at install; serve cache-first with
// background revalidation, so the site works fully offline and still
// picks up new content on the next online visit.
const CACHE = "nife-{version}";
const PRECACHE = {json.dumps(urls, indent=2)};

self.addEventListener("install", e => {{
  e.waitUntil(
    caches.open(CACHE)
      .then(c => Promise.allSettled(PRECACHE.map(u => c.add(u))))
      .then(() => self.skipWaiting())
  );
}});

self.addEventListener("activate", e => {{
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
}});

self.addEventListener("fetch", e => {{
  const url = new URL(e.request.url);
  if (e.request.method !== "GET" || url.origin !== location.origin) return;
  const key = url.origin + url.pathname;   // one cache entry per path, ?v= ignored
  const isPage = e.request.mode === "navigate" ||
    url.pathname.endsWith(".html") || url.pathname.endsWith("/");
  const isScript = url.pathname.endsWith(".js") || url.pathname.endsWith(".css");
  e.respondWith((async () => {{
    const cache = await caches.open(CACHE);
    const cached = await cache.match(key);
    const fetchFresh = () => fetch(e.request)
      .then(resp => {{
        if (resp && resp.ok) cache.put(key, resp.clone());
        return resp;
      }})
      .catch(() => null);
    if (isPage || isScript) {{
      // network-first: always current when online, cached copy offline
      const net = await fetchFresh();
      if (net) return net;
      return cached || new Response("Offline and not cached", {{ status: 503 }});
    }}
    // images/styles: cache-first with background revalidation
    if (cached) {{
      e.waitUntil(fetchFresh());
      return cached;
    }}
    const net = await fetchFresh();
    return net || new Response("Offline and not cached", {{ status: 503 }});
  }})());
}});
"""
open("sw.js", "w").write(sw)
print(f"sw.js written — cache nife-{version}, {len(urls)} URLs precached")
