// Generated by gen-sw.py — do not edit by hand.
// Strategy: precache everything at install; serve cache-first with
// background revalidation, so the site works fully offline and still
// picks up new content on the next online visit.
const CACHE = "nife-de604eb04f";
const PRECACHE = [
  "./",
  "./academics.html",
  "./aero/flashcards.html",
  "./aero/flashcards.js",
  "./aero/index.html",
  "./aero/test-1.html",
  "./aero/test-2.html",
  "./aero/test-3.html",
  "./aero/tests.js",
  "./aero/unit.js",
  "./analytics.js",
  "./apple-touch-icon.png",
  "./engines/diagram-app.js",
  "./engines/diagrams.js",
  "./engines/flashcards.html",
  "./engines/flashcards.js",
  "./engines/img/electrical.png",
  "./engines/img/fuel.png",
  "./engines/img/hydraulic.png",
  "./engines/img/lubrication.png",
  "./engines/index.html",
  "./engines/pumped.html",
  "./engines/system-electrical.html",
  "./engines/system-fuel.html",
  "./engines/system-hydraulic.html",
  "./engines/system-lubrication.html",
  "./engines/test-a.html",
  "./engines/test-b.html",
  "./engines/test-c.html",
  "./engines/test-ch1-3.html",
  "./engines/test-ch4-6.html",
  "./engines/test-ch6-9.html",
  "./engines/tests.js",
  "./engines/unit.js",
  "./favicon.png",
  "./flight-phase-mobile.png",
  "./flight-phase/index.html",
  "./flight-phase/selftest.js",
  "./flight-phase/sim.js",
  "./flight-phase/speech.js",
  "./flight-phase/spoken.js",
  "./fonts/ibm-plex-mono-500.woff2",
  "./fonts/ibm-plex-mono-600.woff2",
  "./fonts/ibm-plex-sans-400.woff2",
  "./fonts/ibm-plex-sans-500.woff2",
  "./fonts/ibm-plex-sans-600.woff2",
  "./fonts/ibm-plex-sans-700.woff2",
  "./frr/flashcards.html",
  "./frr/flashcards.js",
  "./frr/index.html",
  "./frr/test-1.html",
  "./frr/test-2.html",
  "./frr/test-3.html",
  "./frr/test-ch5-1.html",
  "./frr/test-ch5-2.html",
  "./frr/test-ch5-3.html",
  "./frr/tests.js",
  "./frr/unit.js",
  "./ground/data.js",
  "./ground/ep-drill.html",
  "./ground/ep.js",
  "./ground/flashcards.html",
  "./ground/flashcards.js",
  "./ground/index.html",
  "./ground/limits-drill.html",
  "./ground/limits.js",
  "./ground/sheet.html",
  "./ground/sheet.js",
  "./ground/stan-test.html",
  "./ground/stan-tests.js",
  "./ground/stan-unit.js",
  "./ground/test-1.html",
  "./ground/tests.js",
  "./ground/unit.js",
  "./hub.js",
  "./icon-192.png",
  "./icon-512.png",
  "./index.html",
  "./logo-dark.png",
  "./logo-light.png",
  "./manifest.webmanifest",
  "./mobile-nav.png",
  "./quiz.js",
  "./site.js",
  "./style.css",
  "./sw.js",
  "./wx/flashcards.html",
  "./wx/flashcards.js",
  "./wx/index.html",
  "./wx/setai.html",
  "./wx/setai.js",
  "./wx/test-1.html",
  "./wx/test-2.html",
  "./wx/test-3.html",
  "./wx/test-topic1.html",
  "./wx/test-topic2.html",
  "./wx/test-topic3.html",
  "./wx/test-topic4.html",
  "./wx/tests.js",
  "./wx/unit.js",
  "./aero/",
  "./engines/",
  "./frr/",
  "./wx/",
  "./ground/",
  "./flight-phase/"
];

self.addEventListener("install", e => {
  e.waitUntil(
    caches.open(CACHE)
      .then(c => Promise.allSettled(PRECACHE.map(u => c.add(u))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  const url = new URL(e.request.url);
  if (e.request.method !== "GET" || url.origin !== location.origin) return;
  const key = url.origin + url.pathname;   // one cache entry per path, ?v= ignored
  const isPage = e.request.mode === "navigate" ||
    url.pathname.endsWith(".html") || url.pathname.endsWith("/");
  const isScript = url.pathname.endsWith(".js") || url.pathname.endsWith(".css");
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(key);
    const fetchFresh = () => fetch(e.request)
      .then(resp => {
        if (resp && resp.ok) cache.put(key, resp.clone());
        return resp;
      })
      .catch(() => null);
    if (isPage || isScript) {
      // network-first: always current when online, cached copy offline
      const net = await fetchFresh();
      if (net) return net;
      return cached || new Response("Offline and not cached", { status: 503 });
    }
    // images/styles: cache-first with background revalidation
    if (cached) {
      e.waitUntil(fetchFresh());
      return cached;
    }
    const net = await fetchFresh();
    return net || new Response("Offline and not cached", { status: 503 });
  })());
});
