// ============================================================
// STAN EXAM PRACTICE TEST — q: question, o: [options a-d],
// a: correct index, r: rationale, ref: "Sec N — <deck term>".
// Source: NIFE STAN Exam Practice Test (class study set, Quizlet).
// Every question and every answer comes from that set; the twenty
// multiple-choice items are kept word for word with their keyed
// answers, and the recall cards are written as multiple choice.
// Sec 1 = SOP weather/altitude/field limits, Sec 2 = airspace,
// comms and required equipment, Sec 3 = aircraft systems and
// limits, Sec 4 = FTI maneuvers and procedures, Sec 5 = CRM, ORM
// and aeromedical, Sec 6 = mishaps, investigations and reporting.
// ============================================================
const TESTS = [
{
  name: "STAN Exam Practice Test",
  desc: "SOP limits, FTI maneuvers, aircraft systems, CRM/ORM, mishaps",
  questions: [

    // ---- Sec 1: SOP — weather, altitudes, field limits ----
    {q:"Crew day shall not exceed ____ hours and _____ hours should be provided for rest before the next crew day.", o:["10, 10","10, 12","12, 12","12, 10"], a:2, r:"Crew day is capped at 12 hours, and 12 hours of rest are provided before the next crew day — both numbers are the same.", ref:"Sec 1 — Crew day"},
    {q:"Which is not part of the briefing criteria established by the SOP?", o:["I'M SAFE","Weather criteria","Airfield frequencies","ORM"], a:2, r:"I'M SAFE, weather criteria, and ORM are all required briefing items. Airfield frequencies are looked up and used, but they are not part of the SOP briefing criteria.", ref:"Sec 1 — SOP briefing criteria"},
    {q:"Takeoff is not authorized when the weather is below what ceiling and visibility?", o:["A 1000 ft ceiling and 3 SM visibility","A 1500 ft ceiling and 3 SM visibility","A 2000 ft ceiling and 5 SM visibility","A 2500 ft ceiling and 3 SM visibility"], a:1, r:"Takeoff is not authorized with weather below a 1500 ft ceiling and 3 SM visibility. 2500 and 3 is the separate working-area minimum for stalls — do not mix the two.", ref:"Sec 1 — Takeoff weather minimums"},
    {q:"Weather in the working area shall be no less than ______ for either power-off or power-on stalls.", o:["A 1500 ft ceiling and 3 SM visibility","A 2000 ft ceiling and 3 SM visibility","A 2500 ft ceiling and 3 SM visibility","A 3000 ft ceiling and 5 SM visibility"], a:2, r:"Stalls require a 2500 ft ceiling and 3 SM visibility in the working area. 1500 and 3 is the takeoff minimum.", ref:"Sec 1 — Weather limits for stalls"},
    {q:"Recover from stalls shall be no lower than ______.", o:["1000 ft","1500 ft","2000 ft","1200 ft"], a:1, r:"Stall recoveries shall be completed above 1500 ft AGL.", ref:"Sec 1 — Minimum altitudes"},
    {q:"Over NOLF Silverhill, within a 2 NM radius of the center of the field, you shall maintain at or above:", o:["1000 ft MSL","1500 ft MSL","1500 ft AGL","2000 ft MSL"], a:1, r:"1500 ft MSL within 2 NM of the center of the field. Note the reference: stall recoveries use 1500 ft AGL, Silverhill uses 1500 ft MSL — same number, different datum.", ref:"Sec 1 — Minimum altitudes"},
    {q:"What is the criteria for warm-up flights?", o:["Optional on days 7 through 13; mandatory on days 14 through 30, plus one optional","Mandatory on days 7 through 13; optional on days 14 through 30","Optional at any point within a 30-day lapse","Mandatory any time a student has not flown in 7 days"], a:0, r:"Days 7 to 13 a warm-up is optional. Days 14 to 30 one is mandatory, plus one optional.", ref:"Sec 1 — Warm-up flight criteria"},
    {q:"What is the minimum runway distance?", o:["2000 ft","2500 ft","3000 ft","3500 ft"], a:2, r:"3000 ft is the normal runway minimum. 2000 ft is the emergency runway distance — the shorter number only applies when you are already handling an emergency.", ref:"Sec 1 — Runway minimum distance"},
    {q:"What is the minimum runway distance for an emergency?", o:["1500 ft","2000 ft","2500 ft","3000 ft"], a:1, r:"2000 ft for an emergency, versus the 3000 ft normal minimum.", ref:"Sec 1 — Emergency runway distance"},
    {q:"Pattern work at Peter Prince is not authorized when the ceiling is below:", o:["1500 ft","2000 ft","2500 ft","3000 ft"], a:1, r:"No pattern work at Peter Prince with a ceiling below 2000 ft.", ref:"Sec 1 — Peter Prince field restrictions"},
    {q:"May students land in the rain?", o:["Yes, with instructor concurrence","Yes, if visibility is 3 SM or better","No","Only at a towered field"], a:2, r:"No — students do not land in rain.", ref:"Sec 1 — Landing in rain"},
    {q:"Which of the following is NOT required to enter an area of convective SIGMET?", o:["Authorization from the FDO","Maintaining VMC","Continuously monitoring radar","A suitable divert available within 1500 ft / 3 SM"], a:0, r:"The criteria are: maintain VMC, continuously monitor radar, and have a suitable divert available within 1500 ft and 3 SM. Authorization from the FDO is not one of them.", ref:"Sec 1 — Convective SIGMET criteria"},
    {q:"If the weather is not developing as forecast near convective activity, the flight shall:", o:["Maintain VMC, continuously monitor radar, and keep a suitable divert available within 1500 ft / 3 SM","Climb above the weather and continue as filed","Request an IFR clearance and press on","Squawk 7700 and return to base"], a:0, r:"Those three items are the convective SIGMET criteria when the weather is not developing as forecast.", ref:"Sec 1 — Convective SIGMET criteria"},
    {q:"What should be stated as part of the takeoff brief?", o:["Runway remaining, rotate speed, climb out speed","Rotate speed, current winds, departure direction","Rotate speed, departure direction, first maneuver to execute","Rotate speed, climb out speed, departure direction"], a:3, r:"Rotate speed, climb out speed, and departure direction. Winds, runway remaining, and the first maneuver are not part of the brief.", ref:"Sec 1 — Takeoff brief"},
    {q:"Along with rotation speed, climb speed, and departure direction, what else is briefed in the takeoff brief?", o:["Emergency procedures","Current winds","The first maneuver to execute","Runway remaining"], a:0, r:"The takeoff brief components are rotation speed, climb speed, EPs, and departure direction — the EPs are what you will do if it goes wrong on the takeoff roll or just after.", ref:"Sec 1 — Takeoff brief components"},
    {q:"In the preflight brief mnemonic NW KRAFT, what does the K stand for?", o:["Known traffic delays","Known icing conditions","Knots of crosswind","Known airfield closures"], a:0, r:"NW KRAFT is NOTAMs, Weather, Known traffic delays, Runway lengths, Alternate airfields, Fuel requirements, and Takeoff and landing performance.", ref:"Sec 1 — Preflight brief requirements"},

    // ---- Sec 2: Airspace, comms and required equipment ----
    {q:"Pensacola Class C airspace extends up to ____ MSL?", o:["4000","4200","4300","4500"], a:1, r:"Pensacola Class C tops out at 4200 ft MSL.", ref:"Sec 2 — Pensacola Class C"},
    {q:"The see and avoid doctrine includes a scan area of ____ degrees either side and ____ degrees up and down.", o:["60, 10","90, 30","120, 10","60, 50"], a:0, r:"60 degrees either side and 10 degrees up and down — the block of sky where a conflict is actually likely to develop.", ref:"Sec 2 — See and avoid doctrine"},
    {q:"Who do you communicate with at non-towered airports?", o:["Common traffic advisory frequency (CTAF)","Approach control","Center","Flight service on 121.5"], a:0, r:"Position reports go out on CTAF so other traffic in the pattern hears them; there is no controller to talk to.", ref:"Sec 2 — Non-towered airports"},
    {q:"Which frequency band does the military use?", o:["VHF","UHF","HF","VLF"], a:1, r:"UHF is the military band. Civil aviation uses VHF, which is why most Navy aircraft carry both.", ref:"Sec 2 — Military frequency"},
    {q:"Who gives clearance for takeoff?", o:["Ground","Tower","Approach","Clearance delivery"], a:1, r:"Tower owns the runway and issues takeoff clearance. Ground moves you to the runway, approach and clearance delivery do not clear takeoffs.", ref:"Sec 2 — Takeoff clearance"},
    {q:"What is initial contact?", o:["The first call when entering a new facility","The first radio call of the flight","The call made when changing runways","The call made when leaving the pattern"], a:0, r:"Initial contact is your first call when entering a new facility — each new controller gets one.", ref:"Sec 2 — Initial contact"},
    {q:"What are the steps for initial contact, in order?", o:["Who you are calling, who you are, where you are, what you want","Who you are, who you are calling, what you want, where you are","Where you are, who you are, what you want, who you are calling","Who you are calling, what you want, who you are, where you are"], a:0, r:"Who you are calling, who you are, where you are, what you want. The facility name comes first so the controller knows the call is for them.", ref:"Sec 2 — Steps for initial contact"},
    {q:"What squawk code is used for lost comms?", o:["7500","7600","7700","1200"], a:1, r:"7600 is lost comms. 7500 is hijack, 7700 is emergency, and 1200 is VFR.", ref:"Sec 2 — Lost comms squawk"},
    {q:"Which of the following is NOT needed for VFR flight?", o:["A Mode C transponder","An altimeter","An airspeed indicator","Anti-collision lights"], a:0, r:"A Mode C transponder is not required for VFR. The altimeter, airspeed indicator, and anti-collision lights are all on the daytime VFR required equipment list (GOOSEAACAT).", ref:"Sec 2 — VFR requirements"},
    {q:"Daytime VFR required equipment is remembered as GOOSEAACAT. Which of the following is NOT on that list?", o:["Attitude indicator","Emergency locator transmitter","Oil temperature gauge","Anti-collision lights"], a:0, r:"GOOSEAACAT is Gas gauge, Oil pressure gauge, Oil temp gauge, Seatbelts, Emergency locator transmitter, Airspeed indicator, Altimeter, Compass, Anti-collision lights, Tachometer. The attitude indicator is not required for day VFR.", ref:"Sec 2 — Daytime VFR required equipment"},
    {q:"AROW — the documents required on board when the aircraft is operated — stands for:", o:["Airworthiness certificate, registration certificate, operating limitations, weight and balance","Airworthiness certificate, radio license, operating limitations, weather brief","Aircraft logbook, registration, ORM sheet, weight and balance","Airworthiness certificate, registration, owner's manual, waiver"], a:0, r:"Airworthiness certificate, Registration certificate, Operating limitations, and Weight and balance.", ref:"Sec 2 — Required on board when operated"},
    {q:"The altimeter needs to be set within ____ ft of field elevation.", o:["50 ft","75 ft","100 ft","150 ft"], a:1, r:"Within 75 ft of field elevation — if it will not come within that, the altimeter is unusable.", ref:"Sec 2 — Altimeter check"},

    // ---- Sec 3: Aircraft systems and limits ----
    {q:"A Cessna 172 has a ______ powerplant?", o:["Turbine","Reciprocating","Turbo","Mercury"], a:1, r:"The 172 has a reciprocating (piston) engine — pistons driving a crankshaft, not a turbine section.", ref:"Sec 3 — Powerplant"},
    {q:"What horsepower is the Cessna engine rated for?", o:["160 hp","180 hp","200 hp","230 hp"], a:1, r:"The engine is rated at 180 horsepower.", ref:"Sec 3 — Horsepower"},
    {q:"What is the induction system on a Cessna 172?", o:["Fuel injection","Carburetor","Turbocharger","Supercharger"], a:1, r:"A carburetor — which is exactly why carb heat and carb icing are on the checklist and on this exam.", ref:"Sec 3 — Induction system"},
    {q:"What are the optimal conditions for carburetor icing?", o:["Temperature below 70 degrees F and relative humidity above 80%","Temperature below 32 degrees F at any humidity","Temperature above 70 degrees F and humidity above 80%","Temperature below 70 degrees F and humidity below 50%"], a:0, r:"Below 70 degrees F with relative humidity above 80%. Carb ice does not need freezing outside air — the temperature drop happens inside the carburetor.", ref:"Sec 3 — Carb icing conditions"},
    {q:"What are the indications of carburetor icing?", o:["A decrease in engine RPM followed by engine roughness","An increase in RPM followed by a drop in oil pressure","A rise in oil temperature followed by roughness","A drop in manifold pressure with no RPM change"], a:0, r:"RPM decreases first, then the engine runs rough.", ref:"Sec 3 — Carb icing indications"},
    {q:"What RPM drop should you see when carburetor heat is applied?", o:["25 to 50 RPM","50 to 100 RPM","100 to 125 RPM","125 to 175 RPM"], a:1, r:"A 50 to 100 RPM drop. Carb heat feeds the engine warmer, less dense air, so some RPM loss is normal and expected.", ref:"Sec 3 — Carb heat check"},
    {q:"On the magneto check, what drop is expected on each magneto and what is the maximum allowable difference between them?", o:["125 RPM drop each, no more than 50 RPM between them","50 RPM drop each, no more than 125 RPM between them","175 RPM drop each, no more than 50 RPM between them","100 RPM drop each, no more than 100 RPM between them"], a:0, r:"125 RPM drop on each mag, with no greater than 50 RPM variation between the two.", ref:"Sec 3 — Magneto check"},
    {q:"Which of the following instruments would be affected by a power outage?", o:["Turn coordinator","Attitude indicator","Heading indicator","Altimeter"], a:0, r:"The turn coordinator is electrically powered, so it goes with the electrical system. The attitude and heading indicators are air driven and the altimeter is pitot-static.", ref:"Sec 3 — Electrically powered instruments"},
    {q:"Which instruments are powered by air?", o:["Heading indicator and attitude indicator","Turn coordinator and attitude indicator","Airspeed indicator and altimeter","Vertical speed indicator and turn coordinator"], a:0, r:"The heading indicator and the attitude indicator run off air. The turn coordinator is the electric one.", ref:"Sec 3 — Air-powered instruments"},
    {q:"Which port is used for the VSI (vertical speed indicator)?", o:["Static port","Pitot tube","Both the pitot tube and the static port","The alternate air source"], a:0, r:"The VSI is static only. The airspeed indicator is the instrument that needs both pitot and static.", ref:"Sec 3 — VSI"},
    {q:"What affects the magnetic compass?", o:["The aircraft's magnetic field","Electrical load on the bus","Vacuum pump failure","A blocked static port"], a:0, r:"The aircraft's own magnetic field — which is why the compass has a correction card.", ref:"Sec 3 — Magnetic compass"},
    {q:"What components show engine operation?", o:["Oil temperature, oil pressure, and the tachometer","Oil pressure, fuel quantity, and the ammeter","Tachometer, altimeter, and oil temperature","Fuel flow, EGT, and manifold pressure"], a:0, r:"Oil temp, oil pressure, and the tachometer are the three that tell you the engine is actually running the way it should.", ref:"Sec 3 — Engine instruments"},
    {q:"Flaps should not be extended above ______ KIAS?", o:["70","75","80","85"], a:3, r:"85 KIAS is the flap extension limit.", ref:"Sec 3 — Flap limit"},
    {q:"Stall speed with flaps up is _____ and stall speed with flaps full is _____?", o:["50, 40","50, 44","55, 45","52, 44"], a:0, r:"50 KIAS clean, 40 KIAS with full flaps — flaps buy you 10 knots.", ref:"Sec 3 — Stall speeds"},
    {q:"Vy airspeed for a Cessna 172 is ______?", o:["70","73","76","78"], a:1, r:"73 KIAS is Vy, best rate of climb — the most altitude per unit of time.", ref:"Sec 3 — Vy"},
    {q:"Emergency fuel shall be declared when estimated to be ____ remaining at landing and minimum fuel at ______.", o:["10 gal, 5 gal","5 gal, 10 gal","12 gal, 6 gal","6 gal, 12 gal"], a:3, r:"Emergency fuel at an estimated 6 gallons remaining at landing, minimum fuel at 12. Minimum fuel is the advisory; emergency is the declaration, so it is the lower number.", ref:"Sec 3 — Fuel states"},
    {q:"When is it appropriate to lean the mixture?", o:["Cruise","Climb","Descent","In the pattern"], a:0, r:"Cruise. Full rich is used for takeoff, climb, and the pattern where full power may be needed.", ref:"Sec 3 — Leaning the mixture"},

    // ---- Sec 4: FTI maneuvers and procedures ----
    {q:"Per the FTI, a stall recovery consists of?", o:["Max, relax, level, ball","Relax, max, level, ball","Nose up, power on","Nose up, max, level, ball"], a:1, r:"Relax, max, level, ball. Relaxing back pressure comes first — it breaks the stall; power without reducing the angle of attack does not.", ref:"Sec 4 — Stall recovery"},
    {q:"If you are in a stall, should you step on the ball?", o:["Yes","No, use aileron only","Only in a power-on stall","Only if a wing drops more than 30 degrees"], a:0, r:"Yes — ball is the last step of relax, max, level, ball. Rudder keeps the aircraft coordinated so the stall does not turn into a spin.", ref:"Sec 4 — Stall recovery"},
    {q:"Per the FTI, the 4 T's at abeam represent?", o:["Transition, talk, turn, trim","Twist, turn, time, talk","Transition, twist, turn, talk","Transition, trim, turn, talk"], a:3, r:"Transition, trim, turn, talk.", ref:"Sec 4 — 4 T's at abeam"},
    {q:"In the level speed change, what do you establish before beginning?", o:["90 KIAS, altitude, and heading","85 KIAS, altitude, and heading","75 KIAS and full flaps","65 KIAS and 1500 RPM"], a:0, r:"Establish 90 KIAS, altitude, and heading, then carb heat on and power back.", ref:"Sec 4 — Level speed change"},
    {q:"In the level speed change, after carb heat is on, power is reduced to:", o:["1000 RPM","1500 RPM","1700 RPM","2100 RPM"], a:1, r:"Power comes back to 1500 RPM, then flaps go full as the aircraft slows.", ref:"Sec 4 — Level speed change"},
    {q:"In the level speed change, as you approach 55 KIAS, power is increased to:", o:["1500 RPM","1700 RPM","2100 RPM","2300 RPM"], a:2, r:"Approaching 55 KIAS power comes back up to 2100 RPM to hold altitude in slow flight.", ref:"Sec 4 — Level speed change"},
    {q:"Once slow flight is established in the level speed change, what turn is flown?", o:["A 90 degree heading change and back","A 180 degree turn each way","Two 360 degree turns","A 30 degree heading change and back"], a:0, r:"A 90 degree heading change and back.", ref:"Sec 4 — Level speed change"},
    {q:"The recovery from the level speed change is:", o:["Full power, carb heat off, flaps up, 2100 RPM to 90 KIAS","Carb heat on, flaps full, 1500 RPM, 65 KIAS","Full power, flaps up, pitch for Vy, carb heat on","Power to idle, flaps up, 90 KIAS"], a:0, r:"Full power, carb heat off, flaps up, then 2100 RPM back to 90 KIAS.", ref:"Sec 4 — Level speed change"},
    {q:"What RPM range establishes 90 KIAS in cruise?", o:["1500 to 1700 RPM","1700 to 2000 RPM","2100 to 2300 RPM","2300 to 2500 RPM"], a:2, r:"2100 to 2300 RPM establishes 90 KIAS.", ref:"Sec 4 — Cruise RPM and airspeed"},
    {q:"What is the first step of the waveoff procedure?", o:["Power — smooth to max","Carb heat — off","Attitude — increase pitch to slightly above the horizon","Flaps — up"], a:0, r:"Power smooth to max, then carb heat off, attitude to slightly nose above the horizon, flaps raised once airspeed and two positive rates of climb are verified, and finally pitch for Vy.", ref:"Sec 4 — Waveoff procedure"},
    {q:"In the waveoff, when are the flaps raised?", o:["After verifying airspeed and two positive rates of climb","Immediately after power is applied","As soon as carb heat is off","At 400 ft AGL"], a:0, r:"Flaps come up only after airspeed and two positive rates of climb are verified — raising them early trades the lift you just needed.", ref:"Sec 4 — Waveoff procedure"},
    {q:"In the Before Landing checklist, the fuel selector is set to:", o:["BOTH","LEFT","RIGHT","OFF"], a:0, r:"The checklist is Seatbelts and harnesses SECURED, Fuel selector BOTH, Mixture FULL RICH, Landing/taxi lights ON, Carb heat ON, Flaps AS REQUIRED.", ref:"Sec 4 — Before landing checklist"},
    {q:"In the Before Landing checklist, carb heat is set to:", o:["ON","OFF","AS REQUIRED","Left in the cruise position"], a:0, r:"Carb heat ON for landing — the power is coming back, which is when carb ice is most likely.", ref:"Sec 4 — Before landing checklist"},
    {q:"What is the angle of bank range used?", o:["10 to 20 degrees AOB","20 to 45 degrees AOB","30 to 60 degrees AOB","15 to 30 degrees AOB"], a:1, r:"20 to 45 degrees angle of bank.", ref:"Sec 4 — Angle of bank"},
    {q:"In the turn pattern, what angle of bank is used for the 180 degree turn?", o:["15 degrees","30 degrees","45 degrees","60 degrees"], a:2, r:"The turn pattern is: establish 90 KIAS, a 30 degree turn at 15 AOB, a 90 degree turn at 30 AOB, and a 180 degree turn at 45 AOB — the heading change and the bank both step up together.", ref:"Sec 4 — Turn pattern"},
    {q:"In the power-off stall, after clearing turns, carb heat on, and throttle to idle, you:", o:["Go to full flaps, slow to 65 KIAS and descend 200 ft, then pitch nose up 5 to 10 degrees","Slow to 65 KIAS and increase the throttle to 2000 RPM","Pitch nose up 15 to 20 degrees with the flaps up","Hold altitude and wait for the break"], a:0, r:"Full flaps, slow to 65 KIAS while descending 200 ft, then pitch 5 to 10 degrees nose up. The 15 to 20 degree pitch and the power increase belong to the power-on stall.", ref:"Sec 4 — Power off stall"},
    {q:"The recovery from a power-off stall is:", o:["Relax, max, carb heat off, level, ball","Relax, max, level, ball","Max, relax, flaps up, level","Carb heat off, relax, flaps up, ball"], a:0, r:"Relax, max, carb heat off, level, ball — the power-off stall adds carb heat off because carb heat was turned on to set the maneuver up.", ref:"Sec 4 — Power off stall"},
    {q:"In the power-on stall, the throttle is set to ____ as you slow, then increased to ____ before reaching 65 KIAS.", o:["1000 RPM, 2000 RPM","1500 RPM, 2100 RPM","Idle, 2000 RPM","1000 RPM, 2100 RPM"], a:0, r:"Throttle to 1000 RPM to slow, then up to 2000 RPM before 65 KIAS, carb heat off, and pitch up.", ref:"Sec 4 — Power on stall"},
    {q:"In the power-on stall, what pitch attitude is set?", o:["Nose up 5 to 10 degrees","Nose up 15 to 20 degrees","Nose up 20 to 30 degrees","Level pitch until the break"], a:1, r:"15 to 20 degrees nose up for the power-on stall; 5 to 10 degrees is the power-off stall.", ref:"Sec 4 — Power on stall"},
    {q:"Downwind is flown at:", o:["85 KIAS, 1000 ft AGL, half a wing strut from the runway","90 KIAS, 1000 ft AGL, one wing strut from the runway","85 KIAS, 1500 ft AGL, half a wing strut from the runway","75 KIAS, 1000 ft MSL, a full wing strut from the runway"], a:0, r:"85 KIAS, 1000 ft AGL, with the runway half a wing strut out.", ref:"Sec 4 — Downwind"},
    {q:"On a touch and go, what is the first step after touchdown?", o:["Rudder — maintain runway centerline with rudder, no brakes","Flaps — up","Carb heat — off","Power — smoothly apply full power"], a:0, r:"Rudder first to hold centerline with no brakes, then aileron into the crosswind as required, flaps up, carb heat off, power smoothly to full, normal takeoff, and the crosswind turn at 400 ft AGL.", ref:"Sec 4 — Touch and go procedures"},
    {q:"On a touch and go, the crosswind turn is executed at:", o:["300 ft AGL","400 ft AGL","500 ft AGL","Pattern altitude"], a:1, r:"400 ft AGL, with interval and clearance.", ref:"Sec 4 — Touch and go procedures"},
    {q:"What does PAT stand for?", o:["Power, attitude, trim","Pitch, airspeed, trim","Power, airspeed, throttle","Pitch, attitude, throttle"], a:0, r:"Power, attitude, trim — the order you make any change in.", ref:"Sec 4 — PAT"},
    {q:"What happens to aircraft control as airspeed decreases?", o:["Aircraft control decreases disproportionately","Aircraft control decreases proportionally","Aircraft control is unaffected until the stall","Control effectiveness increases as the wing loads up"], a:0, r:"Control decreases disproportionately — the last few knots cost far more control authority than the first few.", ref:"Sec 4 — Slow flight"},
    {q:"With a left headwind, what are the flight control positions?", o:["Ailerons into the wind, elevator neutral","Ailerons away from the wind, elevator neutral","Ailerons into the wind, elevator down","Ailerons neutral, elevator up"], a:0, r:"For a headwind component, turn the ailerons into the wind and leave the elevator neutral — climb into a headwind, dive away from a tailwind.", ref:"Sec 4 — Control positions"},

    // ---- Sec 5: CRM, ORM and aeromedical ----
    {q:"Which of the following skills are part of Crew Resource Management?", o:["Leadership, decisiveness, assertiveness","Compliance, assertiveness, mission analysis","Assertiveness, leadership, communication","Decisiveness, compliance, assertiveness"], a:2, r:"SAD CLAM — Situational awareness, Assertiveness, Decision making, Communication, Leadership, Adaptability, Mission analysis. Decisiveness and compliance are not on the list, so any option containing them is out.", ref:"Sec 5 — Critical skills of CRM"},
    {q:"The critical skills of CRM are remembered as SAD CLAM. What does the M stand for?", o:["Mission analysis","Motivation","Management","Maneuvering"], a:0, r:"Situational awareness, Assertiveness, Decision making, Communication, Leadership, Adaptability, Mission analysis.", ref:"Sec 5 — Critical skills of CRM"},
    {q:"What is situational awareness?", o:["Perception of the current environment","The ability to choose a course of action","Developing short-term and contingency plans","Maintaining a position until convinced by the facts"], a:0, r:"Perception of the current environment. Choosing a course of action is decision making, planning is mission analysis, and holding a position is assertiveness.", ref:"Sec 5 — Situational awareness"},
    {q:"What is detrimental to CRM?", o:["A decrease in situational awareness","An increase in crew workload","Delegating tasks to the crew","Verbalizing the plan out loud"], a:0, r:"A decrease in situational awareness. The other three are normal — and delegating and verbalizing plans are actively good CRM.", ref:"Sec 5 — Detrimental to CRM"},
    {q:"What positively affects decision making?", o:["Teamwork and briefing","Rank and seniority","Time pressure","Task saturation"], a:0, r:"Teamwork and briefing. Time pressure and task saturation degrade decisions, and deferring to rank is a barrier to assertiveness.", ref:"Sec 5 — Decision making"},
    {q:"Which of the following is not a concept that degrades aircrew coordination?", o:["Sandbag syndrome","Excessive professional courtesy","Most conservative response rule","Sudden loss of judgment"], a:2, r:"The most conservative response rule is a solution, not a problem — when the crew disagrees and nobody has better information, you take the most conservative option. The other three all degrade coordination.", ref:"Sec 5 — Aircrew coordination"},
    {q:"The number one cause in over 80% of MISHAPS is ________.", o:["Engine malfunctions","Human error","Maintenance malpractice","Weather related"], a:1, r:"Human error is behind more than 80% of mishaps — which is the reason CRM and ORM exist.", ref:"Sec 5 — Cause of mishaps"},
    {q:"Which one of the following is not a responsibility of the Pilot in Command?", o:["Directly responsible for, and the final authority as to, the operation of that aircraft","May deviate from any rule required to meet an in-flight emergency requiring immediate action","Shall, before beginning a flight, become familiar with all available information concerning that flight","Maintaining the aircraft in an airworthy condition"], a:3, r:"Maintaining the aircraft in an airworthy condition is the owner or operator's responsibility. The PIC must determine the aircraft is airworthy before flight, but keeping it that way is not their job.", ref:"Sec 5 — Pilot in Command"},
    {q:"Which of the following is not considered one of the four principles of ORM?", o:["Accept risks when benefits outweigh the costs","Take no unnecessary risks","Make risk decisions at the right level","Manage risks by accepting no critical risks"], a:3, r:"The fourth principle is anticipate and manage risk by planning — not accepting no critical risks. Some critical risk is accepted when the benefit justifies it.", ref:"Sec 5 — Four principles of ORM"},
    {q:"Which of the following is not considered one of the 5 steps when applying ORM?", o:["Identify obstacles","Identify hazards","Make risk decisions","Supervise"], a:0, r:"The five steps are identify hazards, assess hazards, make risk decisions, implement controls, supervise. Identify obstacles is not one of them.", ref:"Sec 5 — Five steps of ORM"},
    {q:"The five steps of ORM, in order, are:", o:["Identify hazards, assess hazards, make risk decisions, implement controls, supervise","Identify hazards, assess hazards, implement controls, make risk decisions, supervise","Identify hazards, make risk decisions, assess hazards, implement controls, supervise","Assess hazards, identify hazards, make risk decisions, implement controls, supervise"], a:0, r:"Identify, Assess, Make risk decisions, Implement controls, Supervise. You cannot assess a hazard you have not identified, and controls come after the decision.", ref:"Sec 5 — IAM IS process"},
    {q:"What is the last step of the ORM process?", o:["Supervise","Implement controls","Make risk decisions","Assess hazards"], a:0, r:"Supervise — the step that checks the controls are actually working.", ref:"Sec 5 — Five steps of ORM"},
    {q:"The three levels of ORM are:", o:["In-depth, deliberate, time critical","Strategic, operational, tactical","Pre-mission, in-flight, post-mission","Identify, assess, control"], a:0, r:"In-depth, deliberate, and time critical.", ref:"Sec 5 — Three levels of ORM"},
    {q:"The ABCD model for ORM stands for:", o:["Assess the situation, balance resources, communicate to others, do and debrief the event","Analyze, brief, communicate, decide","Assess, balance, control, debrief","Anticipate, brief, communicate, do"], a:0, r:"Assess the situation, Balance resources, Communicate to others, Do and debrief the event — the time-critical tool for when there is no time for the full five steps.", ref:"Sec 5 — ABCD model for ORM"},
    {q:"How do probability and severity differ?", o:["Probability is the likelihood a hazard consequence will occur; severity is the assessment of the potential consequences","Probability is how bad the outcome could be; severity is how often it happens","Both describe how often a hazard is encountered","Probability applies only to deliberate ORM and severity only to time-critical ORM"], a:0, r:"Probability is how likely the consequence is; severity is how bad it would be. Both are needed to place a hazard on the risk assessment matrix.", ref:"Sec 5 — Probability vs severity"},
    {q:"IMSAFE stands for:", o:["Illness, medication, stress, alcohol, fatigue, eating","Illness, motivation, stress, alcohol, fatigue, emotion","Injury, medication, sleep, alcohol, fatigue, eating","Illness, medication, stress, attitude, fatigue, emotion"], a:0, r:"Illness, Medication, Stress, Alcohol, Fatigue, Eating — the personal checklist you run before you ever touch the aircraft.", ref:"Sec 5 — IMSAFE"},
    {q:"What are your 3 priorities, in order, during an emergency?", o:["Navigate, communicate, checklist","Aviate, navigate, checklist","Aviate, navigate, communicate","Aviate, communicate, checklist"], a:2, r:"Aviate, navigate, communicate. Fly the aircraft first — the radio call has never kept anyone airborne.", ref:"Sec 5 — Priority when flying"},
    {q:"If you are lost, the 5 C's are:", o:["Confess, climb, conserve, communicate, comply","Climb, confess, contact, conserve, comply","Confess, climb, contact, coordinate, comply","Climb, communicate, confess, conserve, continue"], a:0, r:"Confess, Climb, Conserve, Communicate, Comply.", ref:"Sec 5 — Lost: 5 C's"},
    {q:"What is GLOC?", o:["Gravity induced loss of consciousness — a temporary loss of consciousness due to changes in acceleration forces","A gradual loss of cabin oxygen at altitude","Loss of control caused by spatial disorientation","Grey-out experienced in a level turn"], a:0, r:"Gravity induced loss of consciousness: an individual temporarily loses consciousness because of changes in acceleration forces.", ref:"Sec 5 — GLOC"},
    {q:"What is the push-pull effect?", o:["Positive G's experienced after negative G's — it can lower G tolerance by 2 to 3 G's and last up to 10 minutes","Negative G's experienced after positive G's, causing red-out","The rapid onset of G during a break turn","The tendency to over-rotate after a pushover"], a:0, r:"Positive G's right after negative G's. Tolerance drops by 2 to 3 G's and the effect can last up to 10 minutes, which is what makes GLOC more likely.", ref:"Sec 5 — Push-pull effect"},
    {q:"What increases G tolerance?", o:["The anti-G straining maneuver (AGSM)","Holding your breath through the turn","Relaxing the abdominal muscles","Leaning forward in the seat"], a:0, r:"The AGSM — the strain plus the breathing cycle keeps blood in the upper body.", ref:"Sec 5 — G tolerance"},

    // ---- Sec 6: Mishaps, investigations and reporting ----
    {q:"The subcategories of mishaps are:", o:["Flight mishap, flight related, aviation ground","Class A, Class B, Class C","HAZREP, SITREP, ASAP","Flight mishap, ground mishap, maintenance mishap"], a:0, r:"Flight mishap, flight related mishap, and aviation ground mishap. Class A through E are the severity classes, not subcategories.", ref:"Sec 6 — Subcategories of mishaps"},
    {q:"A flight mishap is one in which:", o:["There was intent for flight","There was no intent for flight","There was intent for flight but no reportable aircraft damage","The damage exceeds $2.5 million"], a:0, r:"Intent for flight existed. No intent for flight makes it an aviation ground mishap, and intent for flight with no reportable aircraft damage makes it flight related.", ref:"Sec 6 — Flight mishap"},
    {q:"A flight related mishap is one in which:", o:["There was intent for flight and no reportable damage to the aircraft, but it involves a fatality, injury, or property damage","There was intent for flight and reportable damage to the aircraft","There was no intent for flight","The aircraft was destroyed"], a:0, r:"Intent for flight, no reportable damage to the aircraft, but a fatality, injury, or property damage occurred.", ref:"Sec 6 — Flight related mishap"},
    {q:"An aviation ground mishap is one in which:", o:["There was no intent for flight","There was intent for flight but no damage","The mishap occurred while taxiing for takeoff","The damage is less than $25,000"], a:0, r:"No intent for flight — that single fact is what separates it from the other two subcategories.", ref:"Sec 6 — Aviation ground mishap"},
    {q:"For a fixed wing aircraft, intent for flight runs from:", o:["Brake release and/or takeoff power applied, until landed and clear of the runway","Engine start until shutdown","The start of taxi until the aircraft is chocked","Takeoff power applied until full weight is on the landing gear"], a:0, r:"Brake release and/or takeoff power applied until landed clear of the runway. Takeoff power until full weight is on the gear is the helo and tilt-rotor definition.", ref:"Sec 6 — Fixed wing intent for flight"},
    {q:"For a helicopter or tilt-rotor, intent for flight runs from takeoff power applied until:", o:["Full weight is on the skids or landing gear","The aircraft is clear of the landing area","The rotors have stopped","The engines are secured"], a:0, r:"Until full weight is on the skids or landing gear.", ref:"Sec 6 — Helo/tilt intent for flight"},
    {q:"Which class mishap costs greater than $2.5 million in damages?", o:["Class A","Class B","Class C","Class D"], a:0, r:"Class A. It also covers loss of the aircraft, a fatality, or permanent total disability.", ref:"Sec 6 — Class A mishap"},
    {q:"Which mishap investigation board has the ability to take an aviator's wings?", o:["Field Naval Aviator Evaluation Board (FNAEB)","Aircraft Mishap Board (AMB)","JAGMAN investigation","Interagency (NTSB/FAA) investigation"], a:0, r:"The FNAEB evaluates an aviator's performance, potential, and motivation for continued service — it is the board that can end a flying career. The AMB looks for causes, and the JAGMAN looks for negligence and liability.", ref:"Sec 6 — FNAEB"},
    {q:"Who makes up the safety team?", o:["The DH safety officer, the ASO (aviation safety officer), the GSO (ground safety officer), and everyone else","The CO, XO, and department heads only","The ASO and the maintenance officer","The members of the FNAEB"], a:0, r:"The DH safety officer, ASO, GSO — and everyone else. Safety is not just the three billets.", ref:"Sec 6 — Components of the safety team"},
    {q:"What are the ways to report?", o:["ANYMOUSE, ASAP, HAZREP, SITREP","ANYMOUSE, JAGMAN, HAZREP, SITREP","ASAP, HAZREP, SITREP, FNAEB","ANYMOUSE, ASAP, AMB, SITREP"], a:0, r:"ANYMOUSE, ASAP, HAZREPs, and SITREPs. JAGMAN, AMB, and FNAEB are investigations and boards, not reporting programs.", ref:"Sec 6 — Ways to report"},
    {q:"ANYMOUSE is:", o:["An anonymous report placed in a drop box that goes directly to the CO","Voluntary reporting of safety issues and events","A report of any potential hazard that could contribute to a mishap","A report that informs the chain of command of an incident"], a:0, r:"An anonymous drop-box report straight to the CO — no name attached, which is the point.", ref:"Sec 6 — ANYMOUSE"},
    {q:"ASAP (Aviation Safety Awareness Program) is:", o:["Voluntary reporting of safety issues and events","An anonymous drop-box report to the CO","A report that establishes risk severity and exposure for a hazard","A report to the chain of command about an incident"], a:0, r:"Voluntary reporting of safety issues and events. ANYMOUSE is the anonymous one, HAZREP is the hazard one.", ref:"Sec 6 — ASAP"},
    {q:"A HAZREP reports:", o:["Any potential hazard that could contribute to a mishap — bringing awareness to others and establishing risk severity and exposure","Only hazards that have already caused damage","An anonymous complaint routed to the CO","The status of an incident to the chain of command"], a:0, r:"Any potential hazard that could contribute to a mishap. It brings the hazard to everyone's attention and establishes risk severity and exposure.", ref:"Sec 6 — HAZREPs"},
    {q:"A SITREP:", o:["Informs the chain of command of an incident, and is not always aviation related","Is an anonymous report to the CO","Reports a potential hazard for awareness","Is filed only after a Class A mishap"], a:0, r:"A SITREP informs the chain of command of an incident — and the incident does not have to be an aviation one.", ref:"Sec 6 — SITREPs"},
    {q:"Where would you go for a Class A mishap in which aircrew performance is in question?", o:["A FNAEB","A HAZREP","An ANYMOUSE report","A SITREP"], a:0, r:"A Field Naval Aviator Evaluation Board. The others are reporting programs, not boards, and none of them evaluate an aviator's fitness to keep flying.", ref:"Sec 6 — FNAEB"}
  ]
}
];
