// ============================================================
// TEST DATA — q: question, o: [options a-d], a: correct index,
// r: rationale, ref: "Sec N — <deck term>".
// Source: NIFE Ground School class study set (Quizlet).
// Sec 1 = CRM and the seven critical skills, Sec 2 = mishaps,
// classes and investigations, Sec 3 = reporting, IMSAFE,
// wildlife programs and ORM, Sec 4 = aeromedical and G-tolerance.
// ============================================================
const TESTS = [
{
  name: "Ground School Test",
  desc: "CRM, mishaps, investigations, reporting, ORM, IMSAFE",
  questions: [
    // ---- Sec 1: CRM ----
    {q:"According to the study set, a crew day is:", o:["8 hours","10 hours","12 hours","14 hours"], a:2, r:"The deck lists crew day as 12 hours. The other values are not the figure given in the study set.", ref:"Sec 1 — Crew Day"},
    {q:"Crew Resource Management is best defined as:", o:["The effective use of all available resources by individuals, crews, and teams to safely and efficiently accomplish the mission or task","The process of dealing with risk associated with military operations","The ability to direct and coordinate the activities of other crew members and motivate them to work together as a team","The degree of accuracy by which one's perception of the current environment mirrors reality"], a:0, r:"CRM is the effective use of all available resources by individuals, crews, and teams to safely and efficiently accomplish the mission or task. Dealing with risk in military operations defines ORM, directing and motivating the crew is the Leadership skill, and perception mirroring reality is Situational Awareness.", ref:"Sec 1 — Crew Resource Management"},
    {q:"Which of the following is NOT one of the seven critical CRM skills?", o:["Mission Analysis","Teamwork","Assertiveness","Adaptability/Flexibility"], a:1, r:"The seven critical skills are Decision Making, Assertiveness, Mission Analysis, Communication, Leadership, Adaptability/Flexibility, and Situational Awareness. Teamwork appears in the deck only as one of the factors that influence good decision making, not as one of the seven skills.", ref:"Sec 1 — The Seven Critical Skills"},
    {q:"Which CRM skill is defined as the ability to choose a course of action using logical and sound judgment based on all available information?", o:["Mission Analysis","Situational Awareness","Decision Making","Leadership"], a:2, r:"Decision Making is choosing a course of action using logical and sound judgment based on all available information. Mission Analysis is developing plans and coordinating resources, and Situational Awareness is how accurately your perception mirrors reality — it feeds a decision but is not the act of choosing.", ref:"Sec 1 — Decision Making"},
    {q:"Assertiveness is defined in the deck as:", o:["The willingness or readiness to actively participate, state, and maintain a position until convinced by the facts that other options are better","The ability to alter a course of action based on new information and maintain constructive behavior under pressure","The ability to clearly and accurately send and acknowledge information, instructions, or commands","The ability to direct and coordinate the activities of other crew members or wingmen"], a:0, r:"Assertiveness is the willingness to actively participate, state, and maintain a position until convinced by the facts that other options are better — the key is holding the position until facts, not rank, change your mind. Altering course on new information is Adaptability/Flexibility, sending and acknowledging information is Communication, and directing the crew is Leadership.", ref:"Sec 1 — Assertiveness"},
    {q:"Which of the following is NOT listed as a barrier that influences assertiveness?", o:["Position of authority","Qualifications","Task overload","Personal characteristics"], a:2, r:"The barriers to assertiveness are position of authority, experience, rank, qualifications, and personal characteristics — the things that make a crewmember hesitant to speak up. Task overload is one of the factors that influence situational awareness, not an assertiveness barrier.", ref:"Sec 1 — Barriers that influence Assertiveness"},
    {q:"During a flight, you and the other pilot disagree about whether the fuel state allows one more approach, and neither of you has enough information to settle it. According to the assertiveness solutions in the deck, what should the crew do?", o:["Defer to whichever crewmember holds the higher rank","Accept the most conservative response until more information is available","Continue as planned until the disagreement can be resolved on deck","Drop the issue rather than confront the ambiguity"], a:1, r:"One of the listed solutions is to accept the most conservative response to the situation until more information is available. Deferring to rank is exactly the barrier (rank, position of authority) that assertiveness is meant to overcome, pressing on reflects the 'press on regardless' philosophy that degrades situational awareness, and confronting ambiguities — not avoiding them — is another listed solution.", ref:"Sec 1 — Solutions that influence Assertiveness"},
    {q:"Which CRM skill is defined as the ability to develop short-term, long-term, and contingency plans and to coordinate, allocate, and monitor crew and aircraft resources?", o:["Leadership","Decision Making","Situational Awareness","Mission Analysis"], a:3, r:"Mission Analysis covers developing short-term, long-term, and contingency plans and coordinating, allocating, and monitoring crew and aircraft resources; it occurs in three phases — pre-mission, in-flight, and post-mission. Leadership is about directing and motivating the crew, and Decision Making is choosing a course of action — neither is defined by planning and resource allocation.", ref:"Sec 1 — Mission Analysis"},
    {q:"Communication, as a CRM skill, is the ability to:", o:["Direct and coordinate the activities of the other crew members or wingmen","Clearly and accurately send and acknowledge information, instructions, or commands, and provide useful feedback","Maintain constructive behavior under pressure and adapt to internal and external changes","Actively participate, state, and maintain a position until convinced by the facts"], a:1, r:"Communication is clearly and accurately sending and acknowledging information, instructions, or commands and providing useful feedback; the deck's factors for doing it well are communicating clearly, conveying information accurately, being timely, requesting verification or feedback, and verbalizing plans. Directing the crew is Leadership, maintaining constructive behavior under pressure is Adaptability/Flexibility, and maintaining a position until convinced by the facts is Assertiveness.", ref:"Sec 1 — Communication"},
    {q:"Which CRM skill is defined as the ability to direct and coordinate the activities of the other crew members or wingmen, and to motivate the crew to work together as a team?", o:["Leadership","Mission Analysis","Assertiveness","Communication"], a:0, r:"Leadership is directing and coordinating the crew or wingmen and motivating them to work as a team; its traits include delegating tasks, ensuring the crew understands expectations, keeping the crew informed, and providing feedback on performance. Mission Analysis is planning and allocating resources, Assertiveness is maintaining a position until the facts say otherwise, and Communication is sending and acknowledging information.", ref:"Sec 1 — Leadership"},
    {q:"The weather at the destination deteriorates unexpectedly. The pilot calmly revises the plan, diverts to the alternate, and keeps the crew working the problem. Which CRM skill does this best demonstrate?", o:["Assertiveness","Adaptability/Flexibility","Mission Analysis","Decision Making"], a:1, r:"Adaptability/Flexibility is the ability to alter a course of action based on new information, maintain constructive behavior under pressure, and adapt to internal and external changes — the scenario hits all three. Decision Making is involved, but the defining feature here is changing the plan and staying composed through the change, which is the Adaptability/Flexibility definition.", ref:"Sec 1 — Adaptability/Flexibility"},
    {q:"Situational Awareness is defined as:", o:["The ability to choose a course of action using logical and sound judgment","The degree of accuracy by which one's perception of the current environment mirrors reality","The ability to develop short-term, long-term, and contingency plans","The willingness to actively participate and state a position"], a:1, r:"Situational Awareness is the degree of accuracy by which one's perception of the current environment mirrors reality. Choosing a course of action is Decision Making, developing plans is Mission Analysis, and stating a position is Assertiveness.", ref:"Sec 1 — Situational Awareness"},
    {q:"Which of the following is NOT listed as a factor that influences situational awareness?", o:["Task underload","Fatigue/stress","'Press on regardless' philosophy","Position of authority"], a:3, r:"The factors that influence situational awareness are insufficient communication, fatigue/stress, task overload, task underload, the 'press on regardless' philosophy, and degraded operating conditions. Position of authority is a barrier to assertiveness. Note that task underload counts — boredom degrades awareness just as overload does.", ref:"Sec 1 — Factors that influence Situational Awareness"},

    // ---- Sec 2: Mishaps and investigations ----
    {q:"A naval aviation mishap is an unplanned event or series of events that:", o:["Directly involves a defined naval aircraft or UAV and results in damage to DOD or non-DOD property and/or injury or illness to DOD or non-DOD personnel","Directly involves a naval aircraft and results in damage to DOD property only","Occurs only while intent for flight exists and results in $25,000 or more in damage","Involves a naval aircraft and results in the death or permanent total disability of personnel"], a:0, r:"The definition covers a defined naval aircraft or UAV and includes damage to DOD or non-DOD property and injury or illness to DOD or non-DOD personnel. It is not limited to DOD property, it is not limited to intent for flight (aviation ground mishaps are a subcategory), and death or permanent total disability is the Class A threshold, not the definition of a mishap.", ref:"Sec 2 — Naval Aviation Mishap"},
    {q:"For a fixed-wing aircraft, intent for flight begins when:", o:["The engines are started for the mission","Brakes are released (not for taxi) and/or takeoff power is applied, or at the first motion of a catapult shot after the pilot signals","The aircraft first begins to taxi","Takeoff power is applied, and it continues until the landing gear supports the aircraft's weight"], a:1, r:"Fixed-wing intent for flight starts at brake release (not for taxi) and/or takeoff power application, or the first motion of a cat shot after the pilot signals, and it continues until the aircraft taxis free of the runway or landing area or is captured by another recovery system. Engine start and taxi are excluded. Takeoff power until the gear supports the weight is the helicopter/tilt-rotor definition.", ref:"Sec 2 — Intent for Flight, Fixed Wing"},
    {q:"For a helicopter or tilt-rotor, intent for flight continues until:", o:["The aircraft taxis free of the runway or landing area","The aircraft is captured by another recovery system","The skids or landing gear support the aircraft's weight at the termination of flight","The rotors are stopped after shutdown"], a:2, r:"Helo/tilt-rotor intent for flight begins when takeoff power is applied and continues until the skids or landing gear support the aircraft's weight at the termination of flight. Taxiing free of the runway or landing area and capture by another recovery system are the fixed-wing end points.", ref:"Sec 2 — Intent for Flight, Helo/Tilt-Rotor"},
    {q:"Which of the following is NOT one of the three aviation mishap subcategories?", o:["Flight mishap","Flight related mishap","Aviation ground mishap","Hazard report"], a:3, r:"The three subcategories are flight mishaps, flight related mishaps, and aviation ground mishaps. A hazard report (HAZREP) is one of the reporting types, not a mishap subcategory — although a Class E mishap is described as equivalent to a HAZREP.", ref:"Sec 2 — Aviation mishaps subcategories"},
    {q:"An aircraft is a total loss after a landing accident; no one was injured and no dollar figure has been assigned yet. What mishap class is this?", o:["Class A","Class B","Class C","Class D"], a:0, r:"Class A is $2.5 million or more in damage and/or total loss of an aircraft, and/or death or permanent total disability. Total loss of the aircraft alone meets the Class A threshold regardless of the dollar figure or injuries. Class B would require $600,000 up to $2.5 million, permanent partial disability, or three or more personnel hospitalized.", ref:"Sec 2 — Class A Mishap"},
    {q:"A mishap causes $800,000 in damage and one crewmember is hospitalized for inpatient care. What class is it?", o:["Class A","Class B","Class C","Class E"], a:1, r:"The $800,000 damage falls in the Class B range of $600,000 up to $2.5 million. One person hospitalized does not by itself meet the Class B injury criterion (three or more hospitalized for inpatient care), but the cost alone makes it Class B. Class A would require $2.5 million or more, a total loss, or death/permanent total disability.", ref:"Sec 2 — Class B Mishap"},
    {q:"A mishap causes $40,000 in damage and a maintainer misses two workdays because of an injury. What class is it?", o:["Class B","Class C","Class D","Class E"], a:1, r:"One or more lost workdays meets the Class C injury threshold, so the mishap is Class C even though $40,000 sits in the Class D cost range of $25,000 up to $60,000 — a mishap takes the highest class whose criteria it meets. Class E covers cost up to $25,000 or injuries needing only first aid.", ref:"Sec 2 — Class C Mishap"},
    {q:"Which mishap class is defined as $25,000 up to $60,000 in damage, or any recordable injury requiring more than basic first aid?", o:["Class B","Class C","Class D","Class E"], a:2, r:"Class D is $25,000 up to $60,000 or any recordable injury requiring more than basic first aid. Class C starts at $60,000 or one or more lost workdays, and Class E is any cost up to $25,000 or any injury including first aid care.", ref:"Sec 2 — Class D Mishap"},
    {q:"Which mishap class is NOT privileged and is considered equivalent to a HAZREP?", o:["Class B","Class C","Class D","Class E"], a:3, r:"Class E — any cost up to $25,000 or any injury including first aid care — is not privileged and is equivalent to a HAZREP. Classes B, C, and D are investigated with privileged safety information.", ref:"Sec 2 — Class E Mishap"},
    {q:"Which type of mishap investigation convenes an Aircraft Mishap Board (AMB) to determine contributing factors in order to prevent reoccurrence?", o:["JAGMAN investigation","Aviation Mishap Safety Investigation","Interagency investigation","FNAEB/FFPB"], a:1, r:"The Aviation Mishap Safety Investigation convenes an AMB to find contributing factors so the mishap does not happen again. A JAGMAN investigation looks for negligence and liability, the interagency investigation brings in the NTSB and FAA, and the FNAEB/FFPB is an administrative board that evaluates an aviator's continued service.", ref:"Sec 2 — Aviation Mishap Safety Investigation"},
    {q:"The NTSB and FAA can participate in a naval aviation mishap investigation when:", o:["The mishap is Class A or B and aircrew performance is in question","The mishap involves civil aircraft and/or FAA functions, facilities, or personnel","The mishap involves possible negligence or liability","Any mishap occurs off a military installation"], a:1, r:"An interagency investigation brings in the NTSB and FAA whenever a mishap involves civil aircraft and/or FAA functions, facilities, or personnel. Class A or B mishaps with aircrew performance in question trigger a FNAEB/FFPB, and negligence and liability are the purpose of a JAGMAN.", ref:"Sec 2 — Interagency Investigation"},
    {q:"The purpose of a JAGMAN investigation is to:", o:["Determine contributing factors in order to prevent reoccurrence","Evaluate an aviator's performance, potential, and motivation for continued service","Identify possible negligence and liability","Allow those involved to tell the truth without fear of reprisal"], a:2, r:"A JAGMAN investigation exists to identify possible negligence and liability. Determining contributing factors to prevent reoccurrence is the safety investigation (AMB), evaluating an aviator for continued service is the FNAEB/FFPB, and speaking freely without reprisal is the purpose of privileged information.", ref:"Sec 2 — JAGMAN Investigation"},
    {q:"A Field Naval Aviator Evaluation Board (FNAEB) or Field Flight Performance Board (FFPB) is convened:", o:["For any mishap involving civil aircraft","For Class A or B flight mishaps when the aircrew's performance is in question","For every Class A through E mishap","Only after negligence has been established by a JAGMAN"], a:1, r:"The FNAEB (USN) or FFPB (USMC) is an administrative board convened for Class A or B flight mishaps if the aircrew's performance is in question; it evaluates performance, potential, and motivation for continued service as a Naval Aviator before return to flight duties. Civil aircraft involvement triggers an interagency investigation, and the board is not tied to a JAGMAN finding.", ref:"Sec 2 — FNAEB/FFPB"},
    {q:"Privileged information in a mishap safety investigation exists to:", o:["Identify negligence and liability","Allow those involved to tell the truth without fear of reprisal","Determine whether an aviator should continue in flight status","Satisfy NTSB and FAA reporting requirements"], a:1, r:"Privileged information lets those involved tell the truth without fear of reprisal, which is what makes the safety investigation effective at finding causes. Negligence and liability belong to the JAGMAN, flight status decisions to the FNAEB/FFPB, and NTSB/FAA participation to the interagency investigation.", ref:"Sec 2 — Privileged Information"},

    // ---- Sec 3: Reporting, IMSAFE, wildlife, ORM ----
    {q:"Which of the following is NOT one of the four types of accident/incident reporting?", o:["Anymouse","ASAP","HAZREP","JAGMAN"], a:3, r:"The four reporting types are Anymouse, ASAP, HAZREPs, and SITREPs. A JAGMAN is a type of mishap investigation aimed at negligence and liability, not a reporting program.", ref:"Sec 3 — Four types of accident/incident reporting"},
    {q:"In the IMSAFE checklist, the final E stands for:", o:["Eating","Experience","Equipment","Emotion"], a:0, r:"IMSAFE is Illness, Medication, Stress, Alcohol, Fatigue, Eating. Experience is a factor in decision making and a barrier to assertiveness elsewhere in the deck, but it is not part of IMSAFE, and the deck's version uses Eating rather than Emotion for the final letter.", ref:"Sec 3 — IMSAFE checklist"},
    {q:"Which of the following is NOT one of the three wildlife hazard programs?", o:["BASH","BAM","AHAS","ASAP"], a:3, r:"The three wildlife hazard programs are BASH, BAM, and AHAS. ASAP is one of the four accident/incident reporting types.", ref:"Sec 3 — Three types of wildlife hazard programs"},
    {q:"Operational Risk Management is defined as:", o:["The process of dealing with risk associated with military operations","The effective use of all available resources to safely accomplish the mission","Any condition with the potential to negatively impact mission accomplishment","The measure of the likelihood that a potential consequence will occur"], a:0, r:"ORM is the process of dealing with risk associated with military operations. Effective use of all resources is the CRM definition, a condition that could negatively impact the mission is a hazard, and the likelihood of a consequence is probability.", ref:"Sec 3 — Operational Risk Management"},
    {q:"The three levels of ORM are:", o:["Pre-mission, in-flight, and post-mission","In-depth, deliberate, and time critical","Identify, assess, and control","Strategic, operational, and tactical"], a:1, r:"The three levels are in-depth, deliberate, and time critical. Pre-mission, in-flight, and post-mission are the three phases of Mission Analysis, and identify and assess come from the five steps of ORM.", ref:"Sec 3 — Three levels of ORM"},
    {q:"The ABCD model — Assess situation, Balance resources, Communicate to others, Do and Debrief — is applied at which level of ORM?", o:["In-depth","Deliberate","Time critical","Pre-mission"], a:2, r:"The ABCD model is the Time Critical Risk Management tool, used when there is no time for the full five-step process. In-depth and deliberate ORM are the more thorough planning levels, and pre-mission is a phase of Mission Analysis, not an ORM level.", ref:"Sec 3 — Time Critical Risk Management ABCD Model"},
    {q:"Which of the following is NOT one of the four basic principles of ORM?", o:["Accept risk when benefits outweigh the costs","Accept no unnecessary risk","Identify hazards","Make risk decisions at the right level"], a:2, r:"The four principles are: accept risk when benefits outweigh the costs, accept no unnecessary risk, anticipate and manage risk by planning, and make risk decisions at the right level. Identify hazards is the first of the five steps of ORM, not a principle.", ref:"Sec 3 — Four Basic Principles of ORM"},
    {q:"What is the first of the five steps of ORM?", o:["Assess hazards","Identify hazards","Implement controls","Make risk decisions"], a:1, r:"The five steps in order are identify hazards, assess hazards, make risk decisions, implement controls, and supervise. You cannot assess or control a hazard you have not identified, so identification comes first.", ref:"Sec 3 — Five Steps of ORM"},
    {q:"'The measure of the likelihood that, given exposure to a hazard, a potential consequence will occur' defines:", o:["Hazard","Severity","Probability","Risk"], a:2, r:"Probability is the likelihood that a consequence will occur given exposure to a hazard. Severity is the assessment of how bad that potential consequence could be, and a hazard is the condition itself with the potential to cause injury, death, property damage, or mission impact.", ref:"Sec 3 — Probability"},

    // ---- Sec 4: Aeromedical and G-tolerance ----
    {q:"Gravity-Induced Loss of Consciousness (GLOC) is a medical condition in which an individual:", o:["Experiences a temporary loss of consciousness or faints due to changes in acceleration forces, particularly during high-speed/high-G maneuvers","Is more vulnerable to blood pooling because compensating reflexes are unable to spool up","Experiences any condition with the potential to cause injury, death, or property damage","Suffers a permanent total disability as a result of a Class A mishap"], a:0, r:"GLOC is a temporary loss of consciousness or fainting caused by changes in acceleration forces, particularly during high-speed, high-G maneuvers. Blood pooling because reflexes cannot spool up describes the push-pull effect risk (which makes GLOC more likely but is not GLOC itself), a condition with the potential to cause injury is a hazard, and permanent total disability is a Class A mishap criterion.", ref:"Sec 4 — Gravity-Induced Loss of Consciousness"},
    {q:"Why does the push-pull effect increase an individual's vulnerability to GLOC?", o:["The heart rate rises too quickly during the push phase","Blood can pool more easily because of a lack of clamping at the periphery, and the compensating reflexes are unable to 'spool up'","The anti-G suit cannot inflate during negative G","Dehydration occurs faster during rapid G transitions"], a:1, r:"After the negative-G 'push,' the peripheral vessels are not clamped down and the body's compensating reflexes are unable to spool up before the positive-G 'pull,' so blood pools more easily and GLOC comes on more readily. The other options are not the mechanism given in the deck — hydration is a G-tolerance technique, not the push-pull mechanism.", ref:"Sec 4 — Risk Associated with Push-Pull Effect"},
    {q:"Which of the following is listed as a psychological technique to improve physical performance?", o:["Hydration","Acclimatization","Thought and attention control","Conditioning"], a:2, r:"The psychological techniques are adequate sleep, thought and attention control, and arousal control. Hydration, acclimatization, and conditioning are physical techniques for improving G tolerance.", ref:"Sec 4 — Psychological Techniques to improve Physical Performance"},
    {q:"Which of the following is listed as a technique to improve G tolerance?", o:["Arousal control","Acclimatization","Thought and attention control","Adequate sleep"], a:1, r:"The G-tolerance techniques are training, conditioning, hydration, physical fitness, and acclimatization. Arousal control, thought and attention control, and adequate sleep are the psychological techniques to improve physical performance.", ref:"Sec 4 — Techniques to improve G Tolerance"}
  ]
}
];
